# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Keep Magento Secure
tagline:             ''
description:         ''
url:                 http://keepmagentosecure.com
baseurl:             /
paginate:            5
github_repo:         https://github.com/zlik/keepmagentosecure.com

# About/contact
author:
  name:              Oleksandr Zarichnyi
  url:               https://github.com/zlik
  email:             zlikwon@gmail.com

# Custom vars
version:             0.1
